name: Tearraform infra

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      
jobs:
  terraform_init:
    name: Terraform Init
    runs-on: ubuntu-latest
    steps:
      - name: Terraform setup
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Checkout
        uses: actions/checkout@v6

      - name: cd into working folder
        run: cd environment/dev

      - name: Terraform Init
        run: terraform init      

  
  
    



# pipeline level pe agent ko assign ni kar sakte

