name: Greetings Pipeline

on:
  workflow_dispatch:

env:
  NAME: 'sammy'

# pipeline level pe agent ko assign ni kar sakte

jobs:

  Linux-greeting:
    name: reply by linux $name

    runs-on: ubuntu-slim
    steps:
      - name: Hello Audience 
        run: echo "Hello Guys Whats's up, I am good $NAME"     
