name: Tearraform infra

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      
jobs:
  terraform_init:
    name: Terraform Init
    runs-on: ubuntu-latest
    steps:
      - name: Init
        run: terraform working-directory: 
     

  
  
    



# pipeline level pe agent ko assign ni kar sakte

jobs:

  Linux-greeting:
    name: reply by linux $name

    runs-on: ubuntu-slim
    steps:
      - name: Hello Audience 
        run: echo "Hello Guys Whats's up, I am good ${{ github.event.inputs.rgname }}-${{ RUNNER.OS }} "     
