name: Tearraform infra Create

on:
  workflow_dispatch:
  
jobs: 
  terraform:
    uses: sammy856/reusable-workflow/.github/workflows/terraform.yml@main
    with:
      environment: dev
      working_directory: environment
      runner: ubuntu-latest
    secrets: inherit
 
     
