name: Terraform infra Create 

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
 
  push:
    branches:
      - master
 
permissions:
  id-token: write  
  contents: read  
  packages: read
      # issues and pull-requests permissions to write results as pull
      # request comments. Omit them if you don't need summary comments
  issues: write
  pull-requests: write
      # To report GitHub Actions status checks. Omit if you don't need
      # to update commit status
  statuses: write
      
 
jobs:
  super-lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
          persist-credentials: false

      - name: Super-linter
        uses: super-linter/super-linter@v8.5.0 # x-release-please-version
        continue-on-error: true
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          VALIDATE_ALL_CODEBASE: false
          
          VALIDATE_TERRAFORM_TFLINT: true
          VALIDATE_CHECKOV: true
          VALIDATE_TRIVY: true
  


  terraform:
    name: Terraform Setup
    needs: super-lint
    runs-on: arc-runner-set
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    defaults:
      run:
        working-directory: environment/dev
    steps:
      - name: Checkout    
        uses: actions/checkout@v6 

      - name: List files
        run: ls -R

      - name: Debug secrets
        run: |
          echo "CLIENT_ID=${{ secrets.AZURE_CLIENT_ID != '' }}"

      - name: Install Terraform
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
          unzip terraform_1.6.6_linux_amd64.zip
          sudo mv terraform /usr/local/bin/

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: terraform-linters/setup-tflint@v6
        name: Setup TFLint
        with:
          tflint_version: v0.52.0
          cache: true

      - name: Show version
        run: tflint --version

      - name: Run TFLint
        run: tflint -f compact
        continue-on-error: true

    
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          
      - name: Install Checkov
        run: pip install checkov
      
      - name: Run Checkov
        run: checkov -d . --framework terraform
        continue-on-error: true 
        

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: results.sarif
          path: .

   
      - name: Terraform Init
        run: terraform init
        
    
      - name: Terraform Validate
        run: terraform validate
    
      - name: Terraform Plan
        run: terraform plan            

